"""
High-performance simhash implementation in C++

This stub file is mostly autogenerated using pybind11-stubgen, but then manually
changed to use appropriate python typedefs.
"""

from collections.abc import Sequence

from const.types import SimhashHash

__all__: list[str] = [
    "are_near_duplicates",
    "extract_bands",
    "hamming_distance",
    "normalize_text",
    "simhash_128",
    "simhash_128_batch",
]

def are_near_duplicates(h1: SimhashHash, h2: SimhashHash, threshold: int = 5) -> bool:
    """
    Check if two simhashes are within Hamming distance threshold
    """

def extract_bands(hash_value: SimhashHash) -> list[int]:
    """
    Extract 6 band values from a 128-bit simhash
    """

def hamming_distance(h1: SimhashHash, h2: SimhashHash) -> int:
    """
    Compute Hamming distance between two 128-bit simhashes
    """

def normalize_text(text: str) -> str:
    """
    Normalize text by lowercasing
    """

def simhash_128(text: str, ngram_size: int = 5) -> SimhashHash:
    """
    Compute 128-bit simhash for text, returns Python int. The text has a max length of at least 32767 characters.
    """

def simhash_128_batch(texts: Sequence[str], ngram_size: int = 5) -> list[SimhashHash]:
    """
    Batch compute simhashes for multiple texts
    """
